In [2]:
!apt install libomp-dev
!python -m pip install --upgrade faiss-cpu faiss-gpu

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libomp-14-dev libomp5-14
Suggested packages:
  libomp-14-doc
The following NEW packages will be installed:
  libomp-14-dev libomp-dev libomp5-14
0 upgraded, 3 newly installed, 0 to remove and 45 not upgraded.
Need to get 738 kB of archives.
After this operation, 8,991 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libomp5-14 amd64 1:14.0.0-1ubuntu1.1 [389 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libomp-14-dev amd64 1:14.0.0-1ubuntu1.1 [347 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libomp-dev amd64 1:14.0-55~exp2 [3,074 B]
Fetched 738 kB in 0s (2,820 kB/s)
Selecting previously unselected package libomp5-14:amd64.
(Reading database ... 121918 files and directories currently installed.)
Preparing to unpack .../libomp5-14_1%3a

In [3]:
import faiss
import pandas as pd

In [4]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=19UAXN1hoh7xFcLVMVVk7gpSezH70jtJ7' -O database.db

--2024-06-01 13:17:40--  https://docs.google.com/uc?export=download&id=19UAXN1hoh7xFcLVMVVk7gpSezH70jtJ7
Resolving docs.google.com (docs.google.com)... 74.125.134.100, 74.125.134.113, 74.125.134.138, ...
Connecting to docs.google.com (docs.google.com)|74.125.134.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=19UAXN1hoh7xFcLVMVVk7gpSezH70jtJ7&export=download [following]
--2024-06-01 13:17:41--  https://drive.usercontent.google.com/download?id=19UAXN1hoh7xFcLVMVVk7gpSezH70jtJ7&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 173.194.217.132, 2607:f8b0:400c:c13::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|173.194.217.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11632640 (11M) [application/octet-stream]
Saving to: ‘database.db’

database.db         100%[===================>]  11.09M  58.6MB/s    in

In [5]:
import sqlite3

db_con = sqlite3.connect("./database.db")
cur = db_con.cursor()

In [6]:
cur.execute("""
    SELECT post_id, post_text, views
    FROM 'posts'
    ORDER BY post_id
""")

In [7]:
data = pd.DataFrame(cur.fetchall(), columns=['post_id','post_text', 'views'])

In [8]:
data = data.iloc[1: , :]

In [9]:
data = data.set_index('post_id')

In [10]:
data.head(10)

post_text     views
post_id                                                             
5202     🛢Нефть Вrent на лондонской бирже ICE впервые с...  145898.0
5203     ❗️Омбудсмена Татьяну Москалькову госпитализиро...  146885.0
5205     🪶Путин подписал закон о внесудебной блокировке...  138866.0
5206     🤷🏻‍♂️После введения системы QR-кодов количеств...  134041.0
5207     🇩🇪Германия с 7 июля ослабит ковид-ограничения ...  123320.0
5208     В подмосковном Видном неизвестный выстрелил в ...  126068.0
5209     ⚡️На Камчатке пропал с радаров пассажирский са...  115685.0
5210     💉Жителям Москвы рекомендовали оставлять свой н...  115609.0
5212     ⛅️Сегодня москвичей ждёт переменная облачность...  113044.0
5213     🍔Продажи в ресторанах Москвы с введением QR-ко...  174489.0

In [11]:
cur.execute("""
    SELECT post_id, emoji, count
    FROM 'reactions'
    ORDER BY post_id
""")

In [12]:
reactions = pd.DataFrame(cur.fetchall(), columns=['post_id', 'emoji','count'])

In [13]:
reactions.head(10)

post_id emoji  count
0     5202     👍     47
1     5202     🤔     11
2     5202     🗿      7
3     5202     💘      6
4     5202  None      4
5     5202     ❤      3
6     5202     😡      2
7     5202     👎      1
8     5202     😱      1
9     5203     👍     50

In [14]:
reactions_dict = dict()

In [15]:
cur.execute("""
    SELECT p.post_id, p.post_text, GROUP_CONCAT(emoji || count) AS reactions_dictionary
    FROM posts p
    INNER JOIN reactions r ON p.post_id = r.post_id
    GROUP BY p.post_id, post_text;
""")

In [16]:
post_with_reactions = pd.DataFrame(cur.fetchall(), columns=['post_id','post_text', 'reactions'])

In [17]:
post_with_reactions.head(10)

post_id                                          post_text  \
0     5202  🛢Нефть Вrent на лондонской бирже ICE впервые с...   
1     5203  ❗️Омбудсмена Татьяну Москалькову госпитализиро...   
2     5205  🪶Путин подписал закон о внесудебной блокировке...   
3     5206  🤷🏻‍♂️После введения системы QR-кодов количеств...   
4     5207  🇩🇪Германия с 7 июля ослабит ковид-ограничения ...   
5     5208  В подмосковном Видном неизвестный выстрелил в ...   
6     5209  ⚡️На Камчатке пропал с радаров пассажирский са...   
7     5210  💉Жителям Москвы рекомендовали оставлять свой н...   
8     5212  ⛅️Сегодня москвичей ждёт переменная облачность...   
9     5213  🍔Продажи в ресторанах Москвы с введением QR-ко...   

                   reactions  
0  👍47,🤔11,🗿7,💘6,❤3,😡2,👎1,😱1  
1        👍50,🤔21,👎9,🗿9,💘3,❤1  
2               👍33,🤔9,👎5,🗿5  
3                 🤔26,👍12,💘6  
4                  👍16,🤔6,👎2  
5               👎39,👍9,🤔8,😱3  
6           👎16,😱11,👍4,🤔4,❤1  
7               🤔14,👎5,👍1,😡1  
8                     🤔19,👍2  
9                     👍10,🤔3

In [18]:
post_with_reactions = post_with_reactions.set_index('post_id')

###токенизация

In [19]:
!pip install pymorphy2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 55.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=d422feff9720d72098ad39c9c7ffd81a6c4ebbb5e9874454972b6d3257ad1bf2
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt


In [20]:
!pip install emoji

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.4/431.4 kB 8.3 MB/s eta 0:00:00


часть скрипта для обработки текста

In [21]:
import emoji
def remove_emoji(text):
    return emoji.replace_emoji(text[0],'')

In [22]:
cdata = pd.DataFrame(data.apply(remove_emoji,axis=1))

In [23]:
import emoji
import pymorphy2
import re
def tokenizer(data, column):
    cur_column = column
    morph = pymorphy2.MorphAnalyzer()

    def remove_emoji(text):
        return emoji.replace_emoji(text[cur_column],'')

    def remove_punctuation(word: str):
        return re.sub(r'[.,:;]', '', word)

    def encode_num(word: str):
        if word.isnumeric():
            return "I" + str(len(word))
        elif word[1:].isnumeric():  # обработка чисел вида $*
            return word[0] + "I" + str(len(word) - 1)
        else: # обработка чисел вида *$
            return word[-1] + "I" + str(len(word) - 1)

    def lemmatize(data):
        text = data[cur_column]
        words = text.split() # разбиваем текст на слова
        res = []
        for word in words:
            if word.isnumeric() or word[1:].isnumeric() or word[:-1].isnumeric():
                word = encode_num(word)
                res.append(word)
            else:
                word = remove_punctuation(word)
                p = morph.parse(word)[0]
                res.append(p.normal_form)
        return res
    data[cur_column] = data.apply(remove_emoji,axis = 1)
    return data.apply(lemmatize,axis = 1)

In [24]:
tokens = tokenizer(post_with_reactions,'post_text')

In [25]:
tokens[:10]

post_id
5202    [нефть, вrent, на, лондонский, биржа, ice, впе...
5203    [омбудсмен, татьяна, москальков, госпитализиро...
5205    [путин, подписать, закон, о, внесудебный, блок...
5206    [после, введение, система, qr-код, количество,...
5207    [германия, с, I1, июль, ослабить, ковид-ограни...
5208    [в, подмосковный, видный, неизвестный, выстрел...
5209    [на, камчатка, пропасть, с, радар, пассажирски...
5210    [житель, москва, рекомендовать, оставлять, сво...
5212    [сегодня, москвич, ждать, переменный, облачнос...
5213    [продажа, в, ресторан, москва, с, введение, qr...
dtype: object

In [26]:
tokens_list = tokens.to_list()

In [27]:
!wget -c https://github.com/aeksin/datasets/releases/download/new_doc2vec/doc2vec.model

--2024-06-01 13:19:53--  https://github.com/aeksin/datasets/releases/download/new_doc2vec/doc2vec.model
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/761961847/68180eb8-49fd-4d04-8952-6867139d4507?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240601%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240601T131953Z&X-Amz-Expires=300&X-Amz-Signature=bf00eed52af99ab9a66cee7c2266da90a03945d3b223962f96a6a2acbb53c4eb&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=761961847&response-content-disposition=attachment%3B%20filename%3Ddoc2vec.model&response-content-type=application%2Foctet-stream [following]
--2024-06-01 13:19:53--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/761961847/68180eb8-49fd-4d04-8952-6867139d4507?X-Amz-

In [28]:
from gensim.models.doc2vec import Doc2Vec
doc2vec = Doc2Vec.load("doc2vec.model")

In [29]:
vectors_doc = []
import numpy as np
for i in range(len(tokens_list)):
    vectors_doc.append(doc2vec.infer_vector(tokens_list[i]))

In [30]:
from sklearn.cluster import DBSCAN

In [31]:
dbscan_model = DBSCAN()

In [32]:
dbscan_preds = dbscan_model.fit_predict(vectors_doc)

In [33]:
pd.Series(dbscan_preds).value_counts()

-1    8850
 0    1657
Name: count, dtype: int64

In [34]:
vectors_doc_np = np.array(vectors_doc)
vectors_doc_np

array([[-0.02531112, -0.00964816, -0.01764097, ..., -0.04559834,
        -0.01057372,  0.05712707],
       [-0.06670299, -0.07874794, -0.03580619, ..., -0.07420529,
         0.02352639, -0.00807816],
       [-0.0723144 , -0.4421332 , -0.02594732, ...,  0.00988462,
         0.02761311, -0.27630192],
       ...,
       [ 0.1164216 , -0.10471264,  0.02926686, ...,  0.01913482,
        -0.06458104,  0.00259394],
       [-0.03730941, -0.10868434, -0.03167954, ..., -0.03430228,
        -0.07565494,  0.00479424],
       [-0.05115809, -0.13808334, -0.08195416, ..., -0.07600318,
         0.13601646,  0.02991118]], dtype=float32)

In [35]:
stacked = np.hstack((vectors_doc_np,dbscan_preds.reshape((-1,1))))

### create index

In [65]:
import faiss
index = faiss.IndexFlatL2(len(stacked[0]))
index.add(stacked)

In [66]:
stacked.shape

(10507, 201)

In [67]:
num_neighbours = 7
print(stacked[:1])
distances, indices = index.search(stacked[:1], num_neighbours)
print(indices)
print(distances)

[[-2.53111236e-02 -9.64815821e-03 -1.76409651e-02  7.65541419e-02
   1.12386458e-02 -9.82685015e-02 -1.80644915e-03  4.03660089e-02
   5.76522376e-04  1.68788414e-02  1.01892352e-02 -2.31889244e-02
   5.25600277e-02  3.88528854e-02 -1.50422463e-02 -1.65910705e-03
   5.77478223e-02 -3.80556844e-02  1.13856494e-02 -1.75633550e-01
   8.54377523e-02 -3.66948545e-02 -2.86316941e-03  2.37067156e-02
  -7.69705996e-02  2.34263651e-02 -6.35096952e-02 -1.04932934e-02
  -1.86020788e-02 -5.54189943e-02  6.38899356e-02  5.99794835e-02
   2.31966265e-02  3.68178748e-02  2.57263482e-02 -1.27593987e-02
  -1.69497039e-02 -3.73319648e-02 -5.31993583e-02 -1.20814942e-01
  -2.16480512e-02 -8.86637531e-03 -7.85917342e-02  2.25505568e-02
   6.28910214e-02 -3.93353775e-02 -1.65109374e-02 -7.33158439e-02
  -2.61113904e-02  4.25506793e-02  1.27369137e-02 -2.30760928e-02
  -1.12198386e-02  1.47427628e-02  6.07616007e-02 -9.58998979e-04
   1.76431406e-02 -2.76723392e-02 -8.36052969e-02  6.46094829e-02
  -3.04357

In [68]:
distances, indices

(array([[0.        , 0.3918622 , 0.48895085, 0.4919272 , 0.49526456,
         0.50017107, 0.5307618 ]], dtype=float32),
 array([[   0, 2022, 3602, 6576,  145, 6078, 9645]]))

In [69]:
print(tokens_list[0])

['нефть', 'вrent', 'на', 'лондонский', 'биржа', 'ice', 'впервые', 'с', 'I2', 'октябрь', 'I4', 'год', 'подняться', 'выше', '$I2', 'за', 'баррель']


In [70]:
def predict_reactions(post,num_neighbours, index):
    tokens = tokenizer(pd.DataFrame([post], columns = ['text']),'text')
    print(tokens.to_list()[0])
    vectors = doc2vec.infer_vector(tokens.to_list()[0])
    dbscan_preds = dbscan_model.fit_predict(vectors_doc+vectors)[-1]
    print(dbscan_preds)
    vectors = np.hstack((vectors, dbscan_preds))
    vectors = vectors.reshape(1, -1)
    distances, indices = index.search(vectors, num_neighbours)
    reactions_percentage_dict = {}
    def fix(dictionary):
        sum = 0
        for key in dictionary:
            sum+= dictionary[key]
        for key in dictionary:
            dictionary[key]/=sum
    for post in indices:
        reactions = post_with_reactions.iloc[post]['reactions']
        reactions = reactions.iloc[0].split(',')
        total_reactions = 0
        for reaction in reactions:
            cur_reaction = reaction[0]
            number = int(reaction[1:])
            total_reactions += number
        for reaction in reactions:
            cur_reaction = reaction[0]
            number = int(reaction[1:])
            if reaction not in reactions_percentage_dict:
                reactions_percentage_dict[cur_reaction] = number / total_reactions
            else:
                reactions_percentage_dict[cur_reaction] += number / total_reactions
        fix(reactions_percentage_dict)
    return reactions_percentage_dict

In [71]:
stacked = np.hstack((vectors_doc_np,dbscan_preds.reshape((-1,1))))

In [72]:
posts = predict_reactions("рыжие котята бегают по лужайке",10, index)

['рыжий', 'котёнок', 'бегать', 'по', 'лужайка']
-1


In [73]:
posts

{'👍': 0.6223902087832973,
 '👎': 0.22570194384449244,
 '🗿': 0.12239020878329733,
 '💘': 0.029157667386609073,
 '😡': 0.0003599712023038157}

In [74]:
faiss.write_index(index, "simple.index") # по факту то же самое, что и обычный поиск ближайших соседей

### inverted file index

In [75]:
import numpy as np
num_centroids = int(np.sqrt(len(stacked)))
quantiser = faiss.IndexFlatL2(len(stacked[0]))
index = faiss.IndexIVFFlat(quantiser, len(stacked[0]), num_centroids)
index.train(stacked)
index.add(stacked)

In [76]:
reactions_distribution = predict_reactions("рыжие котята бегают по лужайке",10, index)

['рыжий', 'котёнок', 'бегать', 'по', 'лужайка']
-1


In [77]:
reactions_distribution

{'👎': 0.6106194690265486,
 '😱': 0.2627212389380531,
 '❤': 0.10121681415929204,
 '😡': 0.025442477876106196}

In [78]:
faiss.write_index(index, "inverted.index") # сначала ищем самые похожие внутри центроид, а потом уже среди найденных